# This file is used to create a namespace in Kubernetes for the Roboshop project.

apiVersion: v1
kind: Namespace
metadata:
  name: roboshop
  Labels:
  project: roboshop
  environment: dev
  purpose: poc