apiVersion: v1
kind: Pod 
metadata:
  name: resource-demo
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
    #soft limit
    rquests:
      memory: "64Mi"
      cpu: "100m"
    #hard limit
    limits:                 
        memory: "128Mi"
        cpu: "150m"
                 